backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DDTHH:mm:ss",
        }
      - {
          label: "Hero Image",
          name: "heroImage",
          widget: "image",
          required: false,
          media_folder: "/public/uploads",
          public_folder: "/uploads",
        }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "string"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish Date",
          name: "pubDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DDTHH:mm:ss",
        }

      - {
          label: "Hero Image",
          name: "heroImage",
          widget: "image",
          required: false,
          media_folder: "/public/uploads",
          public_folder: "/uploads",
        }
      - {
          label: "Project URL",
          name: "projectUrl",
          widget: "string",
          required: false,
        }
      - {
          label: "Repo URL",
          name: "repoUrl",
          widget: "string",
          required: false,
        }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field:
          label: "Tag"
          name: "tag"
          widget: "string"
      - { label: "Body", name: "body", widget: "markdown" }
